# Generated by Django 6.0.3 on 2026-03-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='id_photo',
            field=models.ImageField(blank=True, null=True, upload_to='id_photos/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='unverified', max_length=20),
        ),
    ]
