# Generated by Django 6.0.3 on 2026-03-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_id_photo_profile_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='trust_score',
            field=models.IntegerField(default=50),
        ),
    ]
