# Generated by Django 4.2.26 on 2026-03-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_price_to_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slag',
            field=models.SlugField(default='_'),
            preserve_default=False,
        ),
    ]
